import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

class MyLocalizations {
  final Locale locale;

  MyLocalizations(this.locale);

  static LocalizationsDelegate<MyLocalizations> delegate =
  MyLocalizationsDelegate();

  static Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'login': "Log in account",
      'subs': "Subscriptions",
      'categories': "Categories",
      'okay': "Okay",
      'emptyfield': "Empty field",
      'enterphone': "Phone number",
      'entername': "Enter name",
      'entercode': "Verification code",
      'changeimg': "Change image",
      'changename': "Change username",
      'sendcode': "Send code",
      'verify': "Verify",
      'signout': "Sign out",
      'settings': "Settings",
      'appearance': "Appearance",
      'common': "Common",
      'clear': "Clear database saves",
      'changelang': "Current language",
      'helpfind': "What you would like to find here?",
      'seeall': "See all",
      'nodata': "No data were founded",
      'warning': "Warning!",
      'clearDB': "Would you like to clear all saves?",
      'cancel': "Cancel",
      'delete': "Delete",
      'information': "Information",
      'moreinfo': "More information",
      'typetext': "Type anything...",
      'favorites': "Bookmarks",
      'newest': "Recently added",
      'popular': "Trending",
      'now': "now",
      'currenttheme': "Current theme",
      'darktheme': "Dark",
      'lighttheme': "Light",
      'systemtheme': "System",
      'themes': "Available themes",
      'langs': "Available languages",
      'systype': "App design",
      'search': "Search here",
      'phrase': "Phrases",
      'openfull': "Open full",
      'back': "Back",
      'next': "Next",
      'continue': "Continue",
      'title1': "Meet new people",
      'desc1': "Chat with someone you liked",
      'account': "Account",
      'piclicense': "Illustrations license",
      'licensetext':
      "Developer: Nick Konnov\nMinsk, Belarus\n\nQuestions:\nnik001301@gmail.com",
      'getstarted': "Let\'s start",
      'loading': "Loading..",
      'all': "All",
      'desc': "Description",
      'tryagain': "Try again",
      'wrongerror': "Something went wrong",
      /////////////////////,
      'addshop': "Add a shop",
      'myshops': "My own shops",
      'transport': "Transport",
      'clothes': "Clothes",
      'plants': "Plants",
      'fooddrinks': "Food&Drinks",
      'other': "Other",
      'clickhere': "Click here...",
      'shopcolor': "Design color:",
    },
    'ru': {
      'login': "Войти в аккаунт",
      'subs': "Подписки",
      'categories': "Категории",
      'okay': "Окей",
      'emptyfield': "Пустые поля",
      'enterphone': "Номер телефона",
      'entername': "Введите название",
      'entercode': "Код подтверждения",
      'changeimg': "Поменять фото",
      'changename': "Поменять имя",
      'sendcode': "Отправить код",
      'verify': "Подтвердить",
      'signout': "Выйти из аккаунта",
      'labels': "Заголовки меню",
      'settings': "Настройки",
      'appearance': "Визуализация",
      'common': "Общие",
      'clear': "Удалить сохранения",
      'changelang': "Текущий язык",
      'helpfind': "Что вы хотели бы здесь найти?",
      'seeall': "Посмотреть все",
      'placestypes': "Места посещения",
      'nodata': "Ничего не найдено",
      'warning': "Внимание!",
      'clearDB': "Вы хотите удалить все сохранения?",
      'cancel': "Отмена",
      'delete': "Удалить",
      'tryservice': "Попробуйте сервис предложенный ниже",
      'information': "Информация",
      'moreinfo': "Больше информации",
      'typetext': "Введите что-нибудь..",
      'searchplace': "Поиск места",
      'favorites': "Закладки",
      'newest': "Новые места",
      'popular': "В топе",
      'now': "сейчас",
      'currenttheme': "Текущая тема",
      'darktheme': "Темная",
      'lighttheme': "Светлая",
      'systemtheme': "Тема устройства",
      'blacktheme': "Черная тема",
      'themes': "Доступные темы",
      'langs': "Доступные языки",
      'systype': "Дизайн приложения",
      'search': "Поиск",
      'phrase': "Фразы",
      'openfull': "Открыть полностью",
      'back': "Назад",
      'next': "Далее",
      'continue': "Продолжить",
      'title1': "Встречайте новых людей",
      'desc1': "Общайтесь с тем, кто вам понравился",
      'account': "Аккаунт",
      'piclicense': "Лицензия изображений",
      'licensetext':
      "Разработчик: Никита Коннов\nМинск, Беларусь\n\nПо вопросам:\nnik001301@gmail.com",
      'getstarted': "Начать",
      'loading': "Загрузка..",
      'all': "Все",
      'desc': "Описание",
      'tryagain': "Попробовать снова",
      'wrongerror': "Что-то пошло не так",
      /////////////////////,
      'addshop': "Создать магазин",
      'myshops': "Мои магазины",
      'transport': "Транспорт",
      'clothes': "Одежда",
      'plants': "Растения",
      'fooddrinks': "Еда&Напитки",
      'other': "Другое",
      'clickhere': "Нажмите здесь...",
      'shopcolor': "Цвет дизайна:",
    },
    'be': {
      'login': "Увайсці ў профіль",
      'subs': "Падпiскi",
      'categories': "Катэгорыi",
      'okay': "Добра",
      'emptyfield': "Пустыя палі",
      'enterphone': "Нумар тэлефона",
      'entercode': "Код пацверджання",
      'changeimg': "Змяніць фота",
      'entername': "Увядзіце назву",
      'changename': "Змяніць імя",
      'sendcode': "Адправіць код",
      'verify': "Пацвердзіць",
      'signout': "Выйсці з профілю",
      'localtime': "Лакальны час:",
      'labels': "Загалоўкi меню",
      'settings': "Налады",
      'appearance': "Вiзуалiзацыя",
      'common': "Агульнае",
      'clear': "Выдаліць захавання",
      'changelang': "Мова прыкладання",
      'helpfind': "Што вы хацелі б тут знайсці?",
      'seeall': "Паглядзець усе",
      'nodata': "Нiчога не знойдзена",
      'warning': "Увага!",
      'clearDB': "Хацiце лi вы выдаліць усе захавання?",
      'cancel': "Адмена",
      'delete': "Выдаліць",
      'tryservice': "Паспрабуйце сэрвіс прапанаваны ніжэй",
      'information': "Iнфармацыя",
      'moreinfo': "Больш інфармацыі",
      'typetext': "Увядзіце што-небудзь..",
      'favorites': "Закладкi",
      'popular': "У топе",
      'now': "зараз",
      'currenttheme': "Тэма прыкладання",
      'darktheme': "Цёмная тэма",
      'lighttheme': "Светлая тэма",
      'systemtheme': "Тэма прылады",
      'blacktheme': "Чорная тэма",
      'themes': "Даступныя тэмы",
      'langs': "Даступныя мовы",
      'systype': "Дизайн приложения",
      'search': "Пошук",
      'openfull': "Адкрыць цалкам",
      'back': "Назад",
      'next': "Далей",
      'continue': "Далей",
      'title1': "Сустракайце новых людзей",
      'desc1': "Кантактуйце з тым, хто вам спадабаўся",
      'account': "Профіль",
      'piclicense': "Ліцэнзія малюнкаў",
      'licensetext':
      "Распрацоўшчык: Мікіта Коннаў\nМiнск, Беларусь\n\nЗ пытаннямi:\nnik001301@gmail.com",
      'getstarted': "Пачаць",
      'appcolor': 'Колер прыкладання',
      'loading': "Загрузка..",
      'all': "Усё",
      'desc': "Апiсанне",
      'tryagain': "Паспрабаваць ізноў",
      'wrongerror': "Нешта пайшло не так",
      /////////////////////,
      'addshop': "Стварыць краму",
      'myshops': "Мае крамы",
      'transport': "Транспарт",
      'clothes': "Адзенне",
      'plants': "Расліны",
      'fooddrinks': "Ежа&Напоі",
      'other': "Iншае",
      'clickhere': "Націсніце тут...",
      'shopcolor': "Колер дызайну:",
    }
  };

  String langCode() => locale.languageCode.toString();

  String translate(key) => _localizedValues[locale.languageCode]![key]!;

  static String of(BuildContext context, String key) =>
      Localizations.of<MyLocalizations>(context, MyLocalizations)!
          .translate(key);
}

class MyLocalizationsDelegate extends LocalizationsDelegate<MyLocalizations> {
  @override
  bool isSupported(Locale locale) =>
      ['en', 'ru', 'be'].contains(locale.languageCode);

  @override
  Future<MyLocalizations> load(Locale locale) =>
      SynchronousFuture<MyLocalizations>(MyLocalizations(locale));

  @override
  bool shouldReload(MyLocalizationsDelegate old) => false;
}
